launch:
  app: greetings:main
services:
  - name: greeting
    service: greetings:GreetingService
    bridge:
      type: schism.bridges.simple_tcp_bridge:SimpleTCPBridge
      host: localhost
      port: 1234
