launch:
  app: greetings:main
services:
  - name: greeting
    service: greetings:GreetingService
    bridge:
      type: schism.bridges.simple_tcp_bridge:SimpleTCPBridge
      serve_on: 0.0.0.0:1234
      middleware:
        - type: greetings:MiddlewareExample
